GET {{baseUrl}}/index
Accept: application/json

###
GET {{baseUrl}}echo/2021
Accept: application/json

###

GET {{baseUrl}}web/order/findAll
Accept: application/json



###
GET {{baseUrl}}web/order/findInfo?id=1
Accept: application/json


###
GET {{baseUrl}}web/order/findInfo?id=1
Accept: application/json

###
GET {{baseUrl}}feign/findAll?id=1
Accept: application/json


### 81
GET {{baseUrl}}index


### 80 gateway
GET {{baseUrl}}api/index

