server:
  tomcat:
    uri-encoding: UTF-8


spring:
  datasource:
    url: jdbc:mysql://mysql.lc:3306/belita?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: belita
    password: CnkGzYxJkeCn2ns7
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization:
      indent_output: true
      fail_on_empty_beans: false
    defaultPropertyInclusion: NON_EMPTY
    deserialization:
      fail_on_unknown_properties: false
    parser:
      allow_unquoted_control_chars: true
      allow_single_quotes: true